### model
model_name_or_path: Qwen/Qwen3-14B
trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_offload_config.json

### dataset
dataset: gem_sft
template: qwen
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/unium/v-haoyutang/gem/qwen_0620
logging_steps: 10
save_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: Hallucination_sft
